name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose run --no-deps web rails new . --force --database=postgresql

- name: Docker Layer Caching
  uses: satackey/action-docker-layer-caching@v0.0.11

